services:
  backend:
    build:
      context: ./server-side
    image: elmtarkati/posapp
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: meaningstocklara
      DB_USERNAME: root
      DB_PASSWORD: 12345679
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 2
        delay: 5s
    working_dir: /var/www
    command: sh -c "until nc -z db 3306; do echo '⏳ Waiting for DB...'; sleep 2; done; php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - db
    volumes:
      - vendor_data:/var/www/vendor # Use prebuilt vendor folder only
      - storage_data:/var/www/storage # Optional: persist storage uploads/logs
      - resources_data:/var/www/resources 

  frontend:
    build:
      context: ./client-side
    image: elmtarkati/front-end-possustem
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345679
      MYSQL_DATABASE: meaningstocklara
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
  vendor_data:
  storage_data:
  resources_data: