services:
  backend:
    build:
      context: ./server-side
    volumes:
      - ./server-side:/var/www
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./client-side
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345679
      MYSQL_DATABASE: meaningstocklara
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
volumes:
  db_data:
networks:
  app-network:
    driver: bridge
