# client-side/Dockerfile

# Build stage
FROM node:18 AS build

WORKDIR /app
COPY package*.json ./
COPY vite.config.* ./
COPY . .

RUN npm install

# Production stage
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*
COPY  /dist /usr/share/nginx/html
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
