# client-side/Dockerfile

# # Build stage
# FROM node:18 AS build

# WORKDIR /app
# COPY package*.json ./
# COPY vite.config.* ./
# COPY . .

# RUN npm install

# # Production stage
# FROM nginx:alpine

# RUN rm -rf /usr/share/nginx/html/*
# COPY  /dist /usr/share/nginx/html
# COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
# ---------- Build stage ----------
FROM node:18 AS build

WORKDIR /app
COPY package*.json ./
COPY vite.config.* ./
RUN npm install

COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine

# Nettoyer l'ancien contenu par sécurité
RUN rm -rf /usr/share/nginx/html/*

# Copier les fichiers buildés vers nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Copier la conf nginx custom
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
